Account Framework was made will add more later this works though.
zmazanv/SpringMilitiaTechConnectZipCodeBank pull request #1
Opened 2023-06-08 20:36 UTC by ev3lasco

2023-06-08 22:34 UTC, zmazanv requested changes

2023-06-08 22:34 UTC, zmazanv commented on src/main/java/bank/connect/tech/service/AccountServices.java
> +        accountRepository.save(account);
This needs reimplementation, considering it doesn't actually do anything different than account creation. Nothing is done with the ID.

2023-06-08 22:34 UTC, zmazanv commented on src/main/java/bank/connect/tech/service/AccountServices.java
> +    public void deleteAccount(Long accountId){
This works for now, but once again, keep in mind that this will need to change in the near future to handle cases where the ID does not exist.

2023-06-08 22:34 UTC, zmazanv commented on src/main/java/bank/connect/tech/service/AccountServices.java
> +//    protected void verifyAccount (Long accountId){
This is a good start. Put it into practice when ready., similarly to the other projects you have already done that make use of something similar.

2023-06-08 22:34 UTC, zmazanv commented on src/main/java/bank/connect/tech/controller/AccountController.java
> +    private AccountServices accountServices;
Refactor to be `AccountService` rather than `AccountServices` as mentioned in the relevant file's comments.

Additionally, throughout the file, I would recommend renaming `accountService` to `this.accountService`. This makes it easier to see at a glance that it is a field that belongs to this class.

2023-06-08 22:34 UTC, zmazanv commented on src/main/java/bank/connect/tech/controller/AccountController.java
> +    @DeleteMapping("/accountId") // just deleting - but I should check if it exists kind of like above:
Ensure that it returns a relevant ResponseEntity. Add the needed failsafes when ready, as you mention. Additionally, correct the path so that it is actually takes a path variable, as you did for your second GET mapping.

2023-06-08 22:34 UTC, zmazanv commented on src/main/java/bank/connect/tech/controller/AccountController.java
> +        if (accountCheck.isPresent()){
Preferably this logic should be implemented in your service. Your controller should not be handling any logic. All it should have to do is provide the needed arguments, pass them into the relevant service method to get the needed result, and that should be it. I provided an example below of what your controller should look like, which is dead simple, simply making the necessary calls without having any logic itself. It should be oblivious to how it actually works. This ensures better modularity, simplicity, readability, and less coupling.

![imagen](https://github.com/zmazanv/SpringMilitiaTechConnectZipCodeBank/assets/95514881/1c960c97-8dfe-446a-a693-dc38c9093f09)

2023-06-08 22:34 UTC, zmazanv commented on src/main/java/bank/connect/tech/controller/AccountController.java
> +    public void updateAccount(Account account, Long id) { // this method takes 2 parameters : the account that I want to update and its ID.
Please view the comments on the deleteAccount method.

2023-06-08 22:34 UTC, zmazanv commented on src/main/java/bank/connect/tech/controller/AccountController.java
> +    public Iterable<Account> getAllAccounts (){
This works, just ensure that it returns a relevant ResponseEntity, as you have done before. Nothing new.

2023-06-08 22:34 UTC, zmazanv commented on src/main/java/bank/connect/tech/controller/AccountController.java
> +    public Optional<Account> getAllAccountById(@PathVariable Long accountId){
Ensure that it returns a relevant ResponseEntity. Additionally, correct the typo so that says "Accounts" rather than "Account".

2023-06-08 22:34 UTC, zmazanv commented on src/main/java/bank/connect/tech/controller/AccountController.java
> +    private AccountRepository accountRepository;
Throughout the file, I would recommend renaming `accountRepository` to `this.accountRepository`. This makes it easier to see at a glance that it is a field that belongs to this class.

2023-06-08 22:34 UTC, zmazanv commented on src/main/java/bank/connect/tech/service/AccountServices.java
> +    private AccountRepository accountRepository;
Throughout the file, I would recommend renaming `accountRepository` to `this.accountRepository`. This makes it easier to see at a glance that it is a field that belongs to this class.

2023-06-09 20:13 UTC, DarusSlah approved these changes

2023-06-09 20:15 UTC, DarusSlah reviewed
make sure your formatting is consistent in all classes

2023-06-09 21:00 UTC, merged