update
zmazanv/SpringMilitiaTechConnectZipCodeBank pull request #4
Opened 2023-06-09 18:54 UTC by MMaldonado1017

Deposit without enums if that was my responsibility

2023-06-09 19:14 UTC, ev3lasco commented on src/main/java/bank/connect/tech/controller/DepositController.java
> +@RequestMapping("/deposits")
According to the task it would be better to not have this here as we do need different URI's that are either accounts/{accountId}/withdrawls so i suggest taking this out and making the custom pathways per annotation.

2023-06-09 19:14 UTC, ev3lasco commented on src/main/java/bank/connect/tech/controller/DepositController.java
> +    @GetMapping("/{id}")
make sure that we are returning relevant ResponseEntities in all of these we will have to add more to make it bulletproof but good start.

2023-06-09 19:14 UTC, ev3lasco commented on src/main/java/bank/connect/tech/controller/DepositController.java
> +    @GetMapping
please use above commenting logic for all of these.

2023-06-09 19:14 UTC, ev3lasco commented on src/main/java/bank/connect/tech/models/Deposit.java
> +    public Deposit() {
Don't need the default constructor here can be deleted.

2023-06-09 19:14 UTC, ev3lasco commented on src/main/java/bank/connect/tech/repositories/DepositRepository.java
> +public interface DepositRepository extends JpaRepository<Deposit, Long> {
extend CrudRepo here instead please

2023-06-09 19:14 UTC, ev3lasco commented on src/main/java/bank/connect/tech/service/DepositService.java
> +@Service
This is a good start we will need to add more to these methods but good for now

2023-06-09 19:22 UTC, MMaldonado1017 commented on src/main/java/bank/connect/tech/repositories/DepositRepository.java
> +public interface DepositRepository extends JpaRepository<Deposit, Long> {
Crud is a JPA repo saying Jpa not only covers crud but many others forget where I got that from but Ik it works

2023-06-09 19:26 UTC, zmazanv commented on src/main/java/bank/connect/tech/repositories/DepositRepository.java
> +public interface DepositRepository extends JpaRepository<Deposit, Long> {
This is just to have consistency across the project since all others are using it, which also works.

2023-06-09 19:28 UTC, MMaldonado1017 commented on src/main/java/bank/connect/tech/controller/DepositController.java
> +@RequestMapping("/deposits")
Im not sure what you are saying right here

2023-06-10 16:17 UTC, ev3lasco requested changes

2023-06-10 16:17 UTC, ev3lasco commented on src/main/java/bank/connect/tech/service/DepositService.java
> +        return depositRepository.save(deposit);
Now we need to add logic to this - when making a deposit - we have to get the account - first and add this to the amount in the account. So make sure to use some logic like this : 
![Screenshot 2023-06-10 120126](https://github.com/zmazanv/SpringMilitiaTechConnectZipCodeBank/assets/127235457/edcbc2f3-77e5-468d-bf2e-bc026f7b5152)

2023-06-10 16:17 UTC, ev3lasco commented on src/main/java/bank/connect/tech/service/DepositService.java
> +        return depositRepository.findById(id).orElse(null);
we need to verify what account this is coming from so you can start implementing a method that verifies accounts - here is some logic as well. 
![Screenshot 2023-06-10 120257](https://github.com/zmazanv/SpringMilitiaTechConnectZipCodeBank/assets/127235457/3679325b-62ef-4b32-85af-bcab72680186)

2023-06-12 00:37 UTC, ev3lasco approved these changes

2023-06-12 00:58 UTC, DarusSlah approved these changes

2023-06-12 01:00 UTC, merged