added Bill POJO and service layer
zmazanv/SpringMilitiaTechConnectZipCodeBank pull request #5
Opened 2023-06-09 18:56 UTC by DarusSlah

added a controller, repository, and other classes for the error response and success response

2023-06-09 19:25 UTC, zmazanv requested changes
This a good start. Let's keep it going. Look at the requested changes please.

2023-06-09 19:25 UTC, zmazanv commented on src/main/java/bank/connect/tech/service/BillService.java
> +    public List<Bill> getAllBills(){
This should be Iterable, rather than List, that way we let Spring handle creation for what it needs exactly, considering it does return an Iterable. This is just for consistency's sake.

2023-06-09 19:25 UTC, zmazanv commented on src/main/java/bank/connect/tech/service/BillService.java
> +        return (List<Bill>) billRepository.findById(account_id).orElse(null);
This should be looked over again considering it is not actually returning what it meant to. Please look at the following example. Additionally make changes that you see fit following the example. Your updateBill method can remain the same as it is fine.

![imagen](https://github.com/zmazanv/SpringMilitiaTechConnectZipCodeBank/assets/95514881/3110dd32-c4e7-48ef-abe9-a5e66bb3116a)

2023-06-09 19:25 UTC, zmazanv commented on src/main/java/bank/connect/tech/repository/BillRepository.java
> +
Ensure that you have the appropriate method that you will need for your BillService. Take the following as an example:

![imagen](https://github.com/zmazanv/SpringMilitiaTechConnectZipCodeBank/assets/95514881/731d9b72-ae19-4fd7-b96b-5ec485a13d69)

2023-06-09 19:25 UTC, zmazanv commented on src/main/java/bank/connect/tech/controller/BillController.java
> +public class BillController {
Please ensure that all methods return a ResponseEntity. Additionally, make sure you have consistent formatting. You can use the following example to make changes:

![imagen](https://github.com/zmazanv/SpringMilitiaTechConnectZipCodeBank/assets/95514881/c15fc3db-b18d-4e8e-af62-f0b6e77dd14a)

2023-06-10 17:41 UTC, ev3lasco approved these changes

2023-06-10 18:09 UTC, zmazanv requested changes
Please make the necessary changes.

2023-06-10 18:09 UTC, zmazanv commented on src/main/java/bank/connect/tech/service/BillService.java
> +    public List<Bill> getAllBills(){
I would suggest changing this to `Iterable<Bill>` to match all other services, especially since the method itself returns an Iterable. No need to specify it further.

2023-06-10 18:09 UTC, zmazanv commented on src/main/java/bank/connect/tech/service/BillService.java
> +        return (List<Bill>) billRepository.findAll();
Because of the above suggestion, the casting would be removed.

2023-06-10 18:09 UTC, zmazanv commented on src/main/java/bank/connect/tech/service/BillService.java
> +    public Iterable<Bill> getBillById(Long id){
This should be returning a `Bill`. Please check your implementation again and make necessary changes to match the required behaviour.

2023-06-10 18:09 UTC, zmazanv commented on src/main/resources/application.properties
This file should be untracked.

2023-06-10 18:09 UTC, zmazanv commented on src/main/java/bank/connect/tech/handler/RestExceptionHandler.java
There is no need to make any changes in here specific to Bill, as you can tune the existing implementation to your specific case. Please restore the original version. This goes along with the comment on the service's verification method.

2023-06-10 18:09 UTC, zmazanv commented on src/main/java/bank/connect/tech/dto/SuccessResponse.java
> +    private List<Bill>data;
The type should not be hard-coded in order to keep it flexible and adaptable to all cases. Look at the above comment and the image attached.

2023-06-10 18:09 UTC, zmazanv commented on src/main/java/bank/connect/tech/dto/SuccessResponse.java
> +public class SuccessResponse {
This should be a generic class. Look at the following examples:

---
![imagen](https://github.com/zmazanv/SpringMilitiaTechConnectZipCodeBank/assets/95514881/e8089220-46a7-438d-b2b3-6208e488911f)
---
![imagen](https://github.com/zmazanv/SpringMilitiaTechConnectZipCodeBank/assets/95514881/0718ce59-a4b6-4e5f-a670-b632edaab24b)
---
![imagen](https://github.com/zmazanv/SpringMilitiaTechConnectZipCodeBank/assets/95514881/1131f9cd-d248-490b-86e3-d54bf4dab7d4)
---

2023-06-10 18:09 UTC, zmazanv commented on src/main/java/bank/connect/tech/controller/BillController.java
> +    public ResponseEntity <Iterable<Bill>> getBillWithId(@PathVariable Long id){
Once again, this should not be returning an `Iterable<Bill>` according to your specification. Look at the comments in the service class for more information.

2023-06-10 19:50 UTC, zmazanv approved these changes
This a good start.

2023-06-10 19:51 UTC, merged